// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/scheduler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromptContinuation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptContinuation) Reset() {
	*x = PromptContinuation{}
	mi := &file_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptContinuation) ProtoMessage() {}

func (x *PromptContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptContinuation.ProtoReflect.Descriptor instead.
func (*PromptContinuation) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *PromptContinuation) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type JobType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*JobType_PromptContinuation
	Type          isJobType_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobType) Reset() {
	*x = JobType{}
	mi := &file_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobType) ProtoMessage() {}

func (x *JobType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobType.ProtoReflect.Descriptor instead.
func (*JobType) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *JobType) GetType() isJobType_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *JobType) GetPromptContinuation() *PromptContinuation {
	if x != nil {
		if x, ok := x.Type.(*JobType_PromptContinuation); ok {
			return x.PromptContinuation
		}
	}
	return nil
}

type isJobType_Type interface {
	isJobType_Type()
}

type JobType_PromptContinuation struct {
	PromptContinuation *PromptContinuation `protobuf:"bytes,100,opt,name=prompt_continuation,json=promptContinuation,proto3,oneof"`
}

func (*JobType_PromptContinuation) isJobType_Type() {}

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Cost          int32                  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	JobType       *JobType               `protobuf:"bytes,4,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubmitJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitJobRequest) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *SubmitJobRequest) GetJobType() *JobType {
	if x != nil {
		return x.JobType
	}
	return nil
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitJobResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubmitJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitJobResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *JobStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type JobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Cost          int32                  `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *JobStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatusResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobStatusResponse) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *JobStatusResponse) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{6}
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobSummary          `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *ListJobsResponse) GetJobs() []*JobSummary {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type JobSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Cost          int32                  `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	WorkerId      string                 `protobuf:"bytes,5,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSummary) Reset() {
	*x = JobSummary{}
	mi := &file_proto_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSummary) ProtoMessage() {}

func (x *JobSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSummary.ProtoReflect.Descriptor instead.
func (*JobSummary) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *JobSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobSummary) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *JobSummary) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *JobSummary) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type RunJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Cost          int32                  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	JobType       *JobType               `protobuf:"bytes,4,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunJobRequest) Reset() {
	*x = RunJobRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobRequest) ProtoMessage() {}

func (x *RunJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobRequest.ProtoReflect.Descriptor instead.
func (*RunJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *RunJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RunJobRequest) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *RunJobRequest) GetJobType() *JobType {
	if x != nil {
		return x.JobType
	}
	return nil
}

type RunJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*RunJobResponse_Queued
	//	*RunJobResponse_Started
	//	*RunJobResponse_Chunk
	//	*RunJobResponse_Completed
	//	*RunJobResponse_Failed
	Event         isRunJobResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunJobResponse) Reset() {
	*x = RunJobResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobResponse) ProtoMessage() {}

func (x *RunJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobResponse.ProtoReflect.Descriptor instead.
func (*RunJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *RunJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunJobResponse) GetEvent() isRunJobResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RunJobResponse) GetQueued() *JobQueued {
	if x != nil {
		if x, ok := x.Event.(*RunJobResponse_Queued); ok {
			return x.Queued
		}
	}
	return nil
}

func (x *RunJobResponse) GetStarted() *JobStarted {
	if x != nil {
		if x, ok := x.Event.(*RunJobResponse_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *RunJobResponse) GetChunk() *OutputChunk {
	if x != nil {
		if x, ok := x.Event.(*RunJobResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *RunJobResponse) GetCompleted() *JobCompleted {
	if x != nil {
		if x, ok := x.Event.(*RunJobResponse_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *RunJobResponse) GetFailed() *JobFailed {
	if x != nil {
		if x, ok := x.Event.(*RunJobResponse_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

type isRunJobResponse_Event interface {
	isRunJobResponse_Event()
}

type RunJobResponse_Queued struct {
	Queued *JobQueued `protobuf:"bytes,100,opt,name=queued,proto3,oneof"`
}

type RunJobResponse_Started struct {
	Started *JobStarted `protobuf:"bytes,101,opt,name=started,proto3,oneof"`
}

type RunJobResponse_Chunk struct {
	Chunk *OutputChunk `protobuf:"bytes,102,opt,name=chunk,proto3,oneof"`
}

type RunJobResponse_Completed struct {
	Completed *JobCompleted `protobuf:"bytes,103,opt,name=completed,proto3,oneof"`
}

type RunJobResponse_Failed struct {
	Failed *JobFailed `protobuf:"bytes,104,opt,name=failed,proto3,oneof"`
}

func (*RunJobResponse_Queued) isRunJobResponse_Event() {}

func (*RunJobResponse_Started) isRunJobResponse_Event() {}

func (*RunJobResponse_Chunk) isRunJobResponse_Event() {}

func (*RunJobResponse_Completed) isRunJobResponse_Event() {}

func (*RunJobResponse_Failed) isRunJobResponse_Event() {}

type JobQueued struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobQueued) Reset() {
	*x = JobQueued{}
	mi := &file_proto_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobQueued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobQueued) ProtoMessage() {}

func (x *JobQueued) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobQueued.ProtoReflect.Descriptor instead.
func (*JobQueued) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{11}
}

type JobStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStarted) Reset() {
	*x = JobStarted{}
	mi := &file_proto_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStarted) ProtoMessage() {}

func (x *JobStarted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStarted.ProtoReflect.Descriptor instead.
func (*JobStarted) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *JobStarted) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type OutputChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputChunk) Reset() {
	*x = OutputChunk{}
	mi := &file_proto_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputChunk) ProtoMessage() {}

func (x *OutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputChunk.ProtoReflect.Descriptor instead.
func (*OutputChunk) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *OutputChunk) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JobCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobCompleted) Reset() {
	*x = JobCompleted{}
	mi := &file_proto_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCompleted) ProtoMessage() {}

func (x *JobCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCompleted.ProtoReflect.Descriptor instead.
func (*JobCompleted) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{14}
}

type JobFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFailed) Reset() {
	*x = JobFailed{}
	mi := &file_proto_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFailed) ProtoMessage() {}

func (x *JobFailed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFailed.ProtoReflect.Descriptor instead.
func (*JobFailed) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *JobFailed) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x15proto/scheduler.proto\x12\x04node\",\n" +
	"\x12PromptContinuation\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"^\n" +
	"\aJobType\x12K\n" +
	"\x13prompt_continuation\x18d \x01(\v2\x18.node.PromptContinuationH\x00R\x12promptContinuationB\x06\n" +
	"\x04type\"|\n" +
	"\x10SubmitJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x05R\x04cost\x12(\n" +
	"\bjob_type\x18\x04 \x01(\v2\r.node.JobTypeR\ajobType\"S\n" +
	"\x11SubmitJobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\"\n" +
	"\x10JobStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x88\x01\n" +
	"\x11JobStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x05R\x04cost\"\x11\n" +
	"\x0fListJobsRequest\"8\n" +
	"\x10ListJobsResponse\x12$\n" +
	"\x04jobs\x18\x01 \x03(\v2\x10.node.JobSummaryR\x04jobs\"\x81\x01\n" +
	"\n" +
	"JobSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x05R\x04cost\x12\x1b\n" +
	"\tworker_id\x18\x05 \x01(\tR\bworkerId\"y\n" +
	"\rRunJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x05R\x04cost\x12(\n" +
	"\bjob_type\x18\x04 \x01(\v2\r.node.JobTypeR\ajobType\"\x93\x02\n" +
	"\x0eRunJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12)\n" +
	"\x06queued\x18d \x01(\v2\x0f.node.JobQueuedH\x00R\x06queued\x12,\n" +
	"\astarted\x18e \x01(\v2\x10.node.JobStartedH\x00R\astarted\x12)\n" +
	"\x05chunk\x18f \x01(\v2\x11.node.OutputChunkH\x00R\x05chunk\x122\n" +
	"\tcompleted\x18g \x01(\v2\x12.node.JobCompletedH\x00R\tcompleted\x12)\n" +
	"\x06failed\x18h \x01(\v2\x0f.node.JobFailedH\x00R\x06failedB\a\n" +
	"\x05event\"\v\n" +
	"\tJobQueued\")\n" +
	"\n" +
	"JobStarted\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"#\n" +
	"\vOutputChunk\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x0e\n" +
	"\fJobCompleted\"!\n" +
	"\tJobFailed\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\x83\x02\n" +
	"\x10SchedulerService\x12<\n" +
	"\tSubmitJob\x12\x16.node.SubmitJobRequest\x1a\x17.node.SubmitJobResponse\x12?\n" +
	"\fGetJobStatus\x12\x16.node.JobStatusRequest\x1a\x17.node.JobStatusResponse\x129\n" +
	"\bListJobs\x12\x15.node.ListJobsRequest\x1a\x16.node.ListJobsResponse\x125\n" +
	"\x06RunJob\x12\x13.node.RunJobRequest\x1a\x14.node.RunJobResponse0\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_proto_rawDescData
}

var file_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_scheduler_proto_goTypes = []any{
	(*PromptContinuation)(nil), // 0: node.PromptContinuation
	(*JobType)(nil),            // 1: node.JobType
	(*SubmitJobRequest)(nil),   // 2: node.SubmitJobRequest
	(*SubmitJobResponse)(nil),  // 3: node.SubmitJobResponse
	(*JobStatusRequest)(nil),   // 4: node.JobStatusRequest
	(*JobStatusResponse)(nil),  // 5: node.JobStatusResponse
	(*ListJobsRequest)(nil),    // 6: node.ListJobsRequest
	(*ListJobsResponse)(nil),   // 7: node.ListJobsResponse
	(*JobSummary)(nil),         // 8: node.JobSummary
	(*RunJobRequest)(nil),      // 9: node.RunJobRequest
	(*RunJobResponse)(nil),     // 10: node.RunJobResponse
	(*JobQueued)(nil),          // 11: node.JobQueued
	(*JobStarted)(nil),         // 12: node.JobStarted
	(*OutputChunk)(nil),        // 13: node.OutputChunk
	(*JobCompleted)(nil),       // 14: node.JobCompleted
	(*JobFailed)(nil),          // 15: node.JobFailed
}
var file_proto_scheduler_proto_depIdxs = []int32{
	0,  // 0: node.JobType.prompt_continuation:type_name -> node.PromptContinuation
	1,  // 1: node.SubmitJobRequest.job_type:type_name -> node.JobType
	8,  // 2: node.ListJobsResponse.jobs:type_name -> node.JobSummary
	1,  // 3: node.RunJobRequest.job_type:type_name -> node.JobType
	11, // 4: node.RunJobResponse.queued:type_name -> node.JobQueued
	12, // 5: node.RunJobResponse.started:type_name -> node.JobStarted
	13, // 6: node.RunJobResponse.chunk:type_name -> node.OutputChunk
	14, // 7: node.RunJobResponse.completed:type_name -> node.JobCompleted
	15, // 8: node.RunJobResponse.failed:type_name -> node.JobFailed
	2,  // 9: node.SchedulerService.SubmitJob:input_type -> node.SubmitJobRequest
	4,  // 10: node.SchedulerService.GetJobStatus:input_type -> node.JobStatusRequest
	6,  // 11: node.SchedulerService.ListJobs:input_type -> node.ListJobsRequest
	9,  // 12: node.SchedulerService.RunJob:input_type -> node.RunJobRequest
	3,  // 13: node.SchedulerService.SubmitJob:output_type -> node.SubmitJobResponse
	5,  // 14: node.SchedulerService.GetJobStatus:output_type -> node.JobStatusResponse
	7,  // 15: node.SchedulerService.ListJobs:output_type -> node.ListJobsResponse
	10, // 16: node.SchedulerService.RunJob:output_type -> node.RunJobResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_scheduler_proto_init() }
func file_proto_scheduler_proto_init() {
	if File_proto_scheduler_proto != nil {
		return
	}
	file_proto_scheduler_proto_msgTypes[1].OneofWrappers = []any{
		(*JobType_PromptContinuation)(nil),
	}
	file_proto_scheduler_proto_msgTypes[10].OneofWrappers = []any{
		(*RunJobResponse_Queued)(nil),
		(*RunJobResponse_Started)(nil),
		(*RunJobResponse_Chunk)(nil),
		(*RunJobResponse_Completed)(nil),
		(*RunJobResponse_Failed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_proto_depIdxs,
		MessageInfos:      file_proto_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_proto = out.File
	file_proto_scheduler_proto_goTypes = nil
	file_proto_scheduler_proto_depIdxs = nil
}
